"""
Data Reader - Read and parse CSV outputs

Utilities for reading CSV files generated by video processing.
"""

import csv
import pandas as pd
from pathlib import Path
from typing import Dict, List, Tuple, Optional


def read_actions_csv(csv_path: str) -> Tuple[float, float, Optional[str], pd.DataFrame]:
    """
    Read actions CSV file.
    
    Format:
    - Line 1: fps,total_duration[,batch_id]
    - Subsequent lines: frame_number,action_label
    
    Args:
        csv_path: Path to actions CSV
    
    Returns:
        Tuple of (fps, total_duration, batch_id, dataframe)
    """
    with open(csv_path, 'r') as f:
        first_line = f.readline().strip().split(',')
        fps = float(first_line[0])
        total_duration = float(first_line[1])
        batch_id = first_line[2] if len(first_line) > 2 else None
    
    # Read rest of data
    df = pd.read_csv(
        csv_path,
        skiprows=1,
        names=['frame', 'action']
    )
    
    return fps, total_duration, batch_id, df


def read_relationships_csv(csv_path: str) -> Tuple[Optional[str], pd.DataFrame]:
    """
    Read relationships CSV file.
    
    Args:
        csv_path: Path to relationships CSV
    
    Returns:
        Tuple of (batch_id, dataframe)
    """
    # Check if first line is batch_id
    with open(csv_path, 'r') as f:
        first_line = f.readline().strip()
        if first_line.startswith('batch_id'):
            batch_id = f.readline().strip().split(',')[1]
            skiprows = 2
        else:
            batch_id = None
            skiprows = 0
    
    # Read data
    df = pd.read_csv(csv_path, skiprows=skiprows)
    
    return batch_id, df


def calculate_action_durations(actions_df: pd.DataFrame, fps: float) -> Dict[str, float]:
    """
    Calculate total duration for each action.
    
    Args:
        actions_df: DataFrame from read_actions_csv
        fps: Frames per second
    
    Returns:
        Dict mapping action -> duration in seconds
    """
    durations = {}
    
    for i in range(len(actions_df)):
        action = actions_df.iloc[i]['action']
        start_frame = actions_df.iloc[i]['frame']
        
        # Get end frame (next action start or end of video)
        if i + 1 < len(actions_df):
            end_frame = actions_df.iloc[i + 1]['frame']
        else:
            # Last action - assume it goes to end
            # This is an approximation
            end_frame = start_frame + 100  # Default
        
        duration = (end_frame - start_frame) / fps
        
        if action in durations:
            durations[action] += duration
        else:
            durations[action] = duration
    
    return durations
